version: '3'

services:
  backend:
    container_name: backend
    build: flask-backend
    command: sh -c "python main.py"
    ports:
      - "8080:8080"

  client:
    container_name: client
    build: front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend